name: Manual github release

on:
  workflow_call:

jobs:
  publish-github:
    name: Publish to GitHub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v7
      with:
        fetch-depth: 0
    - name: Get latest tag
      shell: bash
      run: |
        echo "LATEST=$(git describe --tags --abbrev=0)" >> "$GITHUB_ENV"
        echo "LATEST=$(git describe --tags --abbrev=0)"
    - name: Fetch artifacts
      uses: actions/download-artifact@v8
      with:
        merge-multiple: true
    - name: Calculate checksums
      shell: bash
      run: |
        for tgz in *.tar.gz ; do
          sha256sum ${tgz} > $(basename ${tgz} .tar.gz).sha256
        done
    - name: Release assets
      uses: softprops/action-gh-release@v3
      with:
        tag_name: ${{ env.LATEST }}
        files: |
          *.tar.gz
          *.sha256
      env:
        GITHUB_TOKEN: ${{ github.token }}
